# Generated by Django 4.2.13 on 2024-07-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('releaseDate', models.DateField(max_length=200)),
                ('actors', models.CharField(max_length=200)),
                ('banner', models.ImageField(upload_to='movies')),
                ('trailerLink', models.CharField(max_length=500)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movieapp.genre')),
            ],
        ),
    ]
