# Generated by Django 4.2.13 on 2024-07-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0002_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='imdbrating',
            field=models.CharField(default=0.0, max_length=200),
        ),
    ]
