# Generated by Django 4.2.13 on 2024-08-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0004_movies_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='approval_status',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
