# Generated by Django 4.2.13 on 2024-08-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0005_movies_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='approval_status',
            field=models.IntegerField(default=1, max_length=20),
        ),
    ]
