# Generated by Django 4.2.13 on 2024-08-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0006_alter_movies_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
