# Generated by Django 4.2.13 on 2024-08-05 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movieapp', '0007_alter_movies_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(max_length=100)),
                ('review', models.CharField(max_length=500)),
                ('MovieId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Movieapp.movies')),
                ('UserId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
