# Generated by Django 4.2.13 on 2024-08-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0009_reviews_created_alter_movies_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
